### ISSUE TITLE
scripts don't account for new routes(was urls) output from "cf app foo"

### ISSUE THREAD

**Issue by elfordINTC** [PredixDev/predix-scripts#4]
When running the RMD starter script (quickstart-rmd-ref-app.sh" death occurs with error:
2017-05-25 13:24:09:  --- ERROR: There was an error getting App URI for: ElfyRMD-rmd-datasource
2017-05-25 13:24:09:  --- Running the clean up script... There was an error getting App URI for: ElfyRMD-rmd-datasource

Root causing seems to indicate that two scripts assume that "px app foo" will have a line with "urls" when the current output from px app is "routes" instead.

This problem seems to be scattered around many scripts in this directory with a pattern like:

./rmd-ref-app/predix-scripts/bash/scripts/build-basic-app-data-simulator.sh:    APP_URL=$(px app $DATA_SIMULATOR_APP_NAME | grep urls | awk -F" " '{print $2}')
./rmd-ref-app/predix-scripts/bash/scripts/build-basic-app-dataexchange.sh:    APP_URL=$(px app $DATAEXCHANGE_APP_NAME | grep urls | awk -F" " '{print $2}')
./rmd-ref-app/predix-scripts/bash/scripts/build-basic-app-polymerseed.sh:    apphost=$(px app $FRONT_END_POLYMER_SEED_APP_NAME | grep urls: | awk '{print $2;}')

I believe that pretty much all of these "grep urls" should be "grep routes".  The file that seemed to be either build-basic-app-rmddatasource.sh or curl_helper_funcs.sh.

As another note, some of the scripts seem to grep for "urls" and some seem to grep for a safer "urls:"

**Comment by turnerth** [comment]
I get this on USWest.  It says "urls:".  Can  you paste yours?

px app turnerth-hello-world
Showing health and status for app turnerth-hello-world in org turnerth@ge.com / space dev as turnerth@ge.com...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls: turnerth-hello-world-nonreciprocating-bushman.run.aws-usw02-pr.ice.predix.io
last uploaded: Wed May 24 02:09:39 UTC 2017
stack: cflinuxfs2
buildpack: staticfile_buildpack

     state     since                    cpu    memory         disk         details
#0   running   2017-05-23 07:09:49 PM   0.0%   3.8M of 256M   5.6M of 1G

**Comment by elfordINTC** [comment]
Also on US west.

$ px app ElfyRMD-hello-world
Showing health and status for app ElfyRMD-hello-world in org chris.l.elford@intel.com / space dev as chris.l.elford@intel.com...

name:              ElfyRMD-hello-world
requested state:   started
instances:         1/1
usage:             256M x 1 instances
routes:            elfyrmd-hello-world-vindictive-polygamist.run.aws-usw02-pr.ice.predix.io
last uploaded:     Thu 25 May 14:26:25 PDT 2017
stack:             cflinuxfs2
buildpack:         staticfile_buildpack

     state     since                  cpu    memory         disk         details
#0   running   2017-05-25T21:26:45Z   0.0%   3.7M of 256M   5.6M of 1G

**Comment by turnerth** [comment]
Interesting.  What do you have for this?

cf -v
cf version 6.24.0+c7a32d3a7.2017-02-10
px -v
predix version predix-labs-0.5.4-beta

**Comment by elfordINTC** [comment]
$ cf -v
cf version 6.26.0+9c9a261.2017-04-06
$ px -v
predix version predix-labs-0.5.4-beta

**Comment by elfordINTC** [comment]
The current devbox image uses cf 6.21 and reports "urls"

I'm running on linux where I have installed installed dev tools as per https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1557&tag=1607&journey=Development%20environment&resources=1466,1557,1574,1545 

which points at the most current cf release which is currently cf 6.26 at https://github.com/cloudfoundry/cli/releases

**Comment by turnerth** [comment]
in the process of adding this.  Our git is doing administration so can't check-in.  This will likely go out tomorrow.

local _host=$(px app $1 | grep "urls:" | awk -F" " '{print $2}');
  if [[ -z "$_host" ]]; then
    _host=$(px app $1 | grep "routes:" | awk -F" " '{print $2}')
  fi

**Comment by turnerth** [comment]
A fix went out.  Closing ticket.  Let us know if it didn't go well.

**Comment by elfordINTC** [comment]
yes, the script to set up the RMD reference app works after doing a fresh pull.
Thanks!
