### ISSUE TITLE
Protocol names are consecutive in the URL（https://https://<url>.predix.io）.

### ISSUE THREAD

**Issue by Tomoharu-Kanayama** [PredixDev/predix-scripts#5]
Please check the corresponding part of the file below.

--------------
■predix-scripts\bash\scripts\build-basic-app-dataexchange-ui.sh:
   63:   getUrlForAppName $DATAEXCHANGE_APP_NAME DATAEXCHANGE_URL "https"
   64  
   65    __find_and_replace "\#dataExServiceUrl: .*" "dataExServiceUrl: https://$DATAEXCHANGE_URL" "manifest.yml" "$logDir"

--------------
■predix-scripts\bash\scripts\build-basic-app-nodejs-w-timeseries.sh:
   65:     getUrlForAppName $WINDDATA_SERVICE_APP_NAME WINDDATA_SERVICE_URL "https"
   66  
   67      __find_and_replace "\#windServiceURL: .*" "windServiceURL: https://$WINDDATA_SERVICE_URL" "manifest.yml" "$logDir"
   ..
   82:     __find_and_replace ".*windServiceURL\": .*" "    \"windServiceURL\": \"https://$WINDDATA_SERVICE_URL\"" "server/localConfig.json" "$logDir"

--------------
■predix-scripts\bash\scripts\build-basic-app-polymerseed-rmd.sh:
   79:     getUrlForAppName $WINDDATA_SERVICE_APP_NAME WINDDATA_SERVICE_URL "https"
   80      __find_and_replace "\#windServiceURL: .*" "windServiceURL: https://$WINDDATA_SERVICE_URL" "manifest.yml" "$logDir"
   ..
 104:      setJsonProperty ".development.windServiceURL" https://$WINDDATA_SERVICE_URL "server/localConfig.json" "$logDir"

   83:     getUrlForAppName $RMD_DATASOURCE_APP_NAME RMD_DATASOURCE_URL "https"
   84:     __find_and_replace "\#rmdDatasourceURL: .*" "rmdDatasourceURL: $RMD_DATASOURCE_URL" "manifest.yml" "$logDir"
   ..
 109:      setJsonProperty ".development.rmdDatasourceURL" $RMD_DATASOURCE_URL "server/localConfig.json" "$logDir"

--------------
■predix-scripts\bash\scripts\edge-starter-kit-ui.sh:
   75:   getUrlForAppName $KIT_SERVICE_APP_NAME KIT_SERVICE_URL "https"
   ..
   99    setJsonProperty ".development.kitServiceURL" https://$KIT_SERVICE_URL "server/localConfig.json" "$logDir"

**Comment by gstroup** [comment]
Thanks for raising this issue.  I just discovered this problem too last night.  We're pushing out a fix for this soon.

**Comment by gstroup** [comment]
Fix has been released.  Please let us know if you see any more problems.  Thanks!
